import { NextRequest, NextResponse } from 'next/server';
import fs from 'fs';
import path from 'path';

// Files to sync
const CONTEXT_FILES = ['.gemini.md', '.claude.md', 'agents.md'];

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { action, projectPath, content } = body;

    if (!projectPath) {
      return NextResponse.json({ error: 'projectPath is required' }, { status: 400 });
    }

    // Ensure directory exists (basic validation)
    if (!fs.existsSync(projectPath)) {
      return NextResponse.json({ error: 'Project path does not exist' }, { status: 400 });
    }

    if (action === 'read') {
      // Try to read one of the files to get current context
      let currentContent = '';
      let foundFile = false;

      for (const file of CONTEXT_FILES) {
        const filePath = path.join(projectPath, file);
        if (fs.existsSync(filePath)) {
          currentContent = fs.readFileSync(filePath, 'utf-8');
          foundFile = true;
          break; // Read the first one we find
        }
      }

      if (!foundFile) {
        // If none exist, return a default template
        currentContent = `# Project Context\n\nAutomatically generated by OmniAgent Studio.\n\n## Current Status\n- Initialized context`;
      }

      return NextResponse.json({ content: currentContent });
    }

    if (action === 'sync') {
      if (typeof content !== 'string') {
        return NextResponse.json({ error: 'content is required for sync' }, { status: 400 });
      }

      // Write the identical content to all three context files
      const writeResults = [];
      for (const file of CONTEXT_FILES) {
        const filePath = path.join(projectPath, file);
        try {
          fs.writeFileSync(filePath, content, 'utf-8');
          writeResults.push({ file, status: 'success' });
        } catch (err: any) {
          writeResults.push({ file, status: 'error', message: err.message });
        }
      }

      return NextResponse.json({ success: true, results: writeResults });
    }

    return NextResponse.json({ error: 'Invalid action' }, { status: 400 });

  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
